version: "3.1"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    environment:
      VIRTUAL_HOST: pay.algo-casino.com
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: pay.algo-casino.com
      LETSENCRYPT_EMAIL: admin@algo-casino.com

      # inherit parent env values
      PORT: 5000
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASS:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SLACK_WEBHOOK_URL:

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: payapi
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - db:/var/lib/postgresql
    healthcheck:
      test: "exit 0"

  backup:
    image: kartoza/pg-backup:15-3.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backups:/backups
    environment:
      - DUMPPREFIX=PG
      - POSTGRES_HOST=db
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
  db:
