# syntax=docker/dockerfile:1

# build stage

FROM golang:1.21-alpine AS buildstage

WORKDIR /app

COPY . .
RUN go mod download

RUN go build -o /payapi-worker cmd/worker/*

# deploy stage

FROM alpine:latest

WORKDIR /

COPY --from=buildstage /payapi-worker /payapi-worker

CMD [ "/payapi-worker" ]